### ISSUE TITLE
Issues with patching app in docker

### ISSUE THREAD

**Issue by jozefrebjak** [tattersoftware/codeigniter4-patches#23]
This package is not very usable with Docker development, because of GIT. Dockerized APP don't know about GIT credentials. The best will be add parameters to patch command to specify username & email for GIT. Now I'm added manually before git commands.

```sh
git config --global user.name "USERNAME"
git config --global user.email EMAIL
```

We need add parameters to script to manually specify credentials if needed.

**Comment by MGatner** [comment]
I think adding global credentials to Docker ahead of time is a fine solution. If you want to propose a PR to make this easier I will review it but I don't want it to affect the process for existing credentialed users.

**Comment by MGatner** [comment]
@jozefrebjak Since a functional Git repository is a precondition for `Patches` I'm going to close this as a non-issue. If you have a workaround that you would like to share, or have mentioned in the docs, please send over a PR.
