### ISSUE TITLE
Language/en/Validation.php was created

### ISSUE THREAD

**Issue by kenjis** [tattersoftware/codeigniter4-patches#30]
I upgraded from v4.0.2 to v4.2.10, and `Language/en/Validation.php` was created.
https://github.com/kenjis/codeigniter4login/commit/b1140b2ca35f3cf1ea3967d5a9bf2a0a05c04ff7#diff-5fa1e9d32ce2679e7d1caac4a2875d98e7c26396b5ab37e39a3d5d6d786f1ce0

Is this a bug or expected behavior?

**Comment by MGatner** [comment]
Expected. That file does not exist in 4.0.2 (https://github.com/codeigniter4/CodeIgniter4/tree/4.0.2/app/Language) so when the transition is made Patches detects it as a new file and adds it to your project.

**Comment by kenjis** [comment]
Okay, thanks!
