### ISSUE TITLE
Suggest that shebang includes `-l`

### ISSUE THREAD

**Issue by tangix** [tattersoftware/codeigniter4-patches#32]
Without 100% understanding of any security issues, may I suggest that the `patch` script shebang includes the `-l` option?
Why?
To make sure the shell reads `${HOME}/.profile` during startup and sets up the environment properly. For example I run all `php` and `composer` commands in docker containers and using shell aliases to define these commands. Without `-l`, the startup script is not read and the `patch` command fails with `ERROR 127: Composer must be installed.`

**Comment by MGatner** [comment]
A good suggestion. Would you like to send a PR?

**Comment by MGatner** [comment]
@tangix I did some mild testing and this doesn't seem to affect normal behavior. I wasn't successful with research on security implications. I assume you've been using this locally and it fixes your Docker issues? Let's try it out.
